// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ecommerce/pkg/api"
	"ecommerce/pkg/api/handler"
	"ecommerce/pkg/config"
	"ecommerce/pkg/db"
	"ecommerce/pkg/repository"
	"ecommerce/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config)(*api.ServerHTTP,error){
	gormDB,err:=db.ConnectDB(cfg)
	if err!=nil{
		return nil,err
	}

	offerRepository:=repository.NewOfferRepository(gormDB)
	offerUsecase:=usecase.NewOfferUsecase(offerRepository)
	offerHandler:=handler.NewOfferHandler(offerUsecase)

	orderRepository:=repository.NewOrderRepository(gormDB)

	userRepository:=repository.NewUserRepository(gormDB)
	
	userUsecase:=usecase.NewUserUsecase(userRepository,offerRepository,orderRepository)

	couponRepository:=repository.NewCouponRepository(gormDB)

	orderUsecase:=usecase.NewOrderUsecase(orderRepository,userUsecase,couponRepository)
	orderHandler:=handler.NewOrderHandler(orderUsecase)

	userHandler:=handler.NewUserHandler(userUsecase)

	wishlistRepository:=repository.NewWishlistRepository(gormDB)
	wishlistUsecase:=usecase.NewWishlistUsecase(wishlistRepository)
	wishlistHandler:=handler.NewWishlistHandler(wishlistUsecase)

	adminRepository :=repository.NewAdminRepository(gormDB)
	adminUsecase:=usecase.NewAdminUsecase(adminRepository)
	adminHandler:=handler.NewAdminHandler(adminUsecase)

	

	

	inventoryRepository:=repository.NewInventoryRepository(gormDB)
	inventoryUsecase:=usecase.NewInventoryUsecase(inventoryRepository)
	inventoryHandler:=handler.NewInventoryHandler(inventoryUsecase)

	categoryRepository:=repository.NewCategoryRepository(gormDB)
	categoryUsecase:=usecase.NewCategoryUsecase(categoryRepository)
	categoryHandler:=handler.NewCategoryHandler(categoryUsecase)

	paymentRepo:=repository.NewPaymentRepository(gormDB)
	paymentUsecase:=usecase.NewPaymentUsecase(paymentRepo,userRepository)
	paymentHandler:=handler.NewPaymentHandler(paymentUsecase)

	cartRepository:=repository.NewCartRepository(gormDB)
	cartUsecase:=usecase.NewCartUsecase(cartRepository,inventoryRepository,userUsecase,paymentUsecase)
	cartHandler:=handler.NewCartHandler(cartUsecase)

	
	couponUsecase:=usecase.NewCouponUsecase(couponRepository)
	couponHandler:=handler.NewCouponHandler(couponUsecase)


	otpRepository:=repository.NewOtpRepository(gormDB)
	otpUsecase:=usecase.NewOtpUsecase(cfg,otpRepository)
	otpHandler:=handler.NewOtpHandler(otpUsecase)

	serverHTTP:=api.NewServerHttp(categoryHandler,inventoryHandler,userHandler,otpHandler,adminHandler,cartHandler,orderHandler,paymentHandler,wishlistHandler,offerHandler,couponHandler)

	return serverHTTP,nil
}